# Generated by Django 4.0.3 on 2022-08-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigation_app', '0002_litigation_mc_residui'),
    ]

    operations = [
        migrations.AddField(
            model_name='litigation',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
