# Generated by Django 4.0.5 on 2022-08-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litigation_app', '0003_litigation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='contract_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='origin',
            field=models.CharField(default='admin', max_length=10),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='residual_surface',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
