# Generated by Django 4.0.3 on 2022-08-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('hubspot_card', models.URLField(blank=True, null=True)),
                ('customer_type', models.CharField(choices=[('company', 'company'), ('individual', 'individual')], default='individual', max_length=30)),
                ('company_name', models.CharField(blank=True, max_length=50)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('vat_number', models.CharField(blank=True, max_length=30)),
                ('fiscal_code', models.CharField(blank=True, max_length=30)),
                ('birth_place', models.CharField(blank=True, max_length=100)),
                ('birthday', models.CharField(blank=True, max_length=10)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('phone_prefix', models.CharField(blank=True, choices=[('+39', '+39'), ('+355', '+355'), ('+44', '+44'), ('+43', '+43'), ('+32', '+32'), ('+359', '+359'), ('+357', '+357'), ('+420', '+420'), ('+45', '+45'), ('+372', '+372'), ('+358', '+358'), ('+33', '+33'), ('+49', '+49'), ('+30', '+30'), ('+36', '+36'), ('+354', '+354'), ('+353', '+353'), ('+371', '+371'), ('+423', '+423'), ('+370', '+370'), ('+352', '+352'), ('+356', '+356'), ('+31', '+31'), ('+47', '+47'), ('+48', '+48'), ('+351', '+351'), ('+40', '+40'), ('+421', '+421'), ('+386', '+386'), ('+34', '+34'), ('+46', '+46'), ('+383', '+383'), ('+389', '+389'), ('+382', '+382'), ('+381', '+381'), ('+41', '+41'), ('+90', '+90'), ('+380', '+380')], default='+39', max_length=4)),
                ('mobile_prefix', models.CharField(blank=True, choices=[('+39', '+39'), ('+355', '+355'), ('+44', '+44'), ('+43', '+43'), ('+32', '+32'), ('+359', '+359'), ('+357', '+357'), ('+420', '+420'), ('+45', '+45'), ('+372', '+372'), ('+358', '+358'), ('+33', '+33'), ('+49', '+49'), ('+30', '+30'), ('+36', '+36'), ('+354', '+354'), ('+353', '+353'), ('+371', '+371'), ('+423', '+423'), ('+370', '+370'), ('+352', '+352'), ('+356', '+356'), ('+31', '+31'), ('+47', '+47'), ('+48', '+48'), ('+351', '+351'), ('+40', '+40'), ('+421', '+421'), ('+386', '+386'), ('+34', '+34'), ('+46', '+46'), ('+383', '+383'), ('+389', '+389'), ('+382', '+382'), ('+381', '+381'), ('+41', '+41'), ('+90', '+90'), ('+380', '+380')], default='+39', max_length=4)),
                ('street', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('post_number', models.CharField(blank=True, max_length=50)),
                ('is_customer', models.BooleanField(default=False, verbose_name='Customer')),
                ('origin', models.CharField(default='js', max_length=10)),
                ('is_active', models.BooleanField(default=False, verbose_name='Closed')),
            ],
        ),
    ]
