# Generated by Django 4.0.3 on 2022-07-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('initial_value', models.CharField(max_length=100)),
                ('objective_value', models.CharField(max_length=100)),
                ('final_value', models.CharField(max_length=100)),
                ('moltiplicatore', models.CharField(max_length=100)),
                ('revue_value', models.CharField(max_length=100)),
                ('total_cost_value', models.CharField(max_length=100)),
                ('EBIT', models.CharField(max_length=100)),
                ('EBIt_percent', models.CharField(max_length=100)),
            ],
        ),
    ]
