# Generated by Django 4.0.5 on 2022-08-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='EBIt_percent',
            field=models.CharField(max_length=100, verbose_name='EBIT %'),
        ),
    ]
