# Generated by Django 4.0.5 on 2022-08-30 12:28

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard_page', '0002_alter_statistic_ebit_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kpi',
            fields=[
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPI',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dashboard_page.statistic',),
        ),
    ]
